name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      solana:
        image: solanalabs/solana:v1.8.0
        options: --entrypoint /bin/sh
        ports:
          - 8899:8899
        env:
          - RUST_LOG=info
        options: >-
          --health-cmd "solana-test-validator --version"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal
        override: true

    - name: Install Solana and Anchor
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.8.0/install)"
        cargo install --git https://github.com/project-serum/anchor anchor-cli --locked

    - name: Build and Test
      run: |
        solana-test-validator --reset &
        sleep 10
        anchor test
        
